### ISSUE TITLE
expect().be_true is rspec2 syntax; `rspec` command does not work

### ISSUE THREAD

**Issue by cielavenir** [tbpgr/tbpgr_utils#3]
Even with the fresh clone, `rake spec` fails in together_sample_spec.rb.

OSX 10.10.1, Ruby 2.0.0p481

**Comment by cielavenir** [comment]
I found https://github.com/rspec/rspec-expectations/issues/560 .
It means modification of `expect(first_ret).to be_true` to `expect(first_ret).to be true` is correct.
How do you think?

**Comment by cielavenir** [comment]
Now I rechecked the Gemfile and it turned out that I need to `bundle exec rspec` instead. Now you can close this issue if you wish. I'm very sorry.

**Comment by cielavenir** [comment]
Of course if you are going to upgrade to rspec3, it should be better...

**Comment by tbpgr** [comment]
Ok.Thanks.
