### ISSUE TITLE
Refactor split('') to each_char

### ISSUE THREAD

**Issue by tbpgr** [tbpgr/tbpgr_utils#5]
refactor
`split('')`
to
`each_char`

https://github.com/tbpgr/tbpgr_utils/blob/master/lib/open_classes/integer/each_digit.rb#L11
https://github.com/tbpgr/tbpgr_utils/blob/master/lib/open_classes/integer/each_digit_with_index.rb#L11
https://github.com/tbpgr/tbpgr_utils/blob/master/lib/open_classes/integer/reverse_each_digit.rb#L11

**Comment by cielavenir** [comment]
By the way, Nabetani-san says each_char.to_a is slightly faster than split(''). How do you feel (about String#uniq)?

**Comment by cielavenir** [comment]
I cannot find the source. My memory might be wrong...
